# Generated by Django 5.2.8 on 2025-11-07 20:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import functools
import runner.models.problem_data
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('statement', models.TextField(blank=True, verbose_name='Условие')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('rating', models.IntegerField(default=800, validators=[django.core.validators.MinValueValidator(800), django.core.validators.MaxValueValidator(3000)], verbose_name='Рейтинг сложности')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.FloatField(verbose_name='Метрика')),
                ('log', models.TextField(verbose_name='Лог проверки')),
                ('errors', models.TextField(blank=True, verbose_name='Ошибки')),
                ('file_name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Время отправки')),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('error', 'Ошибка')], default='success', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Отчёт',
                'verbose_name_plural': 'Отчёты',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Новый блокнот', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notebooks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_type', models.CharField(choices=[('code', 'Code'), ('latex', 'LaTeX')], default='code', max_length=16)),
                ('content', models.TextField(blank=True)),
                ('output', models.TextField(blank=True)),
                ('execution_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='runner.notebook')),
            ],
            options={
                'ordering': ['execution_order'],
            },
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('_type', models.IntegerField(blank=True, db_column='type')),
                ('difficulty', models.IntegerField(blank=True)),
                ('start_time', models.DateField()),
                ('duration', models.IntegerField(blank=True)),
                ('status', models.IntegerField(choices=[(0, 'going'), (1, 'after-solving')], default=0)),
                ('open', models.IntegerField(choices=[(0, 'closed'), (1, 'opened')], default=0)),
                ('leaderBoard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runner.leaderboard')),
                ('problems', models.ManyToManyField(blank=True, to='runner.problem')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='submissions/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', '⏳ В очереди'), ('running', '🏃 Выполняется'), ('accepted', '✅ Принято'), ('failed', '❌ Ошибка'), ('validated', '✅ Валидировано')], default='pending', max_length=20)),
                ('code_size', models.PositiveIntegerField(default=0)),
                ('metrics', models.JSONField(blank=True, null=True)),
                ('problem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='runner.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_file', models.FileField(blank=True, null=True, upload_to=functools.partial(runner.models.problem_data._problem_file_path, *('train',), **{}))),
                ('test_file', models.FileField(blank=True, null=True, upload_to=functools.partial(runner.models.problem_data._problem_file_path, *('test',), **{}))),
                ('sample_submission_file', models.FileField(blank=True, null=True, upload_to=functools.partial(runner.models.problem_data._problem_file_path, *('sample_submission',), **{}))),
                ('answer_file', models.FileField(blank=True, null=True, upload_to=functools.partial(runner.models.problem_data._problem_file_path, *('answer',), **{}))),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='runner.problem')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['problem'], name='runner_prob_problem_7dd32b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProblemDescriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_column', models.CharField(default='id', max_length=100)),
                ('target_column', models.CharField(default='prediction', max_length=100)),
                ('id_type', models.CharField(choices=[('int', 'Integer'), ('str', 'String')], default='int', max_length=20)),
                ('target_type', models.CharField(choices=[('float', 'Float'), ('int', 'Integer'), ('str', 'String')], default='float', max_length=20)),
                ('check_order', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='descriptor', to='runner.problem')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['problem'], name='runner_prob_problem_211b79_idx')],
            },
        ),
        migrations.CreateModel(
            name='PreValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('warnings', 'Warnings')], default='failed', max_length=20)),
                ('errors_count', models.PositiveIntegerField(default=0)),
                ('warnings_count', models.PositiveIntegerField(default=0)),
                ('rows_total', models.BigIntegerField(blank=True, null=True)),
                ('unique_ids', models.BigIntegerField(blank=True, null=True)),
                ('first_id', models.CharField(blank=True, max_length=255, null=True)),
                ('last_id', models.CharField(blank=True, max_length=255, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('errors', models.JSONField(default=list)),
                ('warnings', models.JSONField(default=list)),
                ('stats', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prevalidation', to='runner.submission')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['submission', 'created_at'], name='runner_prev_submiss_881dc9_idx')],
            },
        ),
    ]
