# Generated by Django 5.2.7 on 2025-11-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0002_problem_author_problem_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemdescriptor',
            name='metric',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
