# Generated by Django 5.2.8 on 2025-11-20 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0003_alter_notebook_owner'),
        ('runner', '0003_problem_descriptor_metrics'),
    ]

    operations = [
    ]
