# Generated by Django 5.2.8 on 2025-11-20 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0004_merge_20251120_1835'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='cell_type',
            field=models.CharField(choices=[('code', 'Code'), ('latex', 'LaTeX'), ('text', 'Text')], default='code', max_length=16),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notebooks', to=settings.AUTH_USER_MODEL),
        ),
    ]
