# Generated by Django 5.2.7 on 2025-11-25 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0003_problemdescriptor_metric'),
        ('runner', '0004_report_test_data_alter_cell_cell_type'),
    ]

    operations = [
    ]
