# Generated by Django 5.2.8 on 2025-11-26 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0006_merge_manual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contest',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='contest',
            name='_type',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='leaderBoard',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='open',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='status',
        ),
        migrations.AddField(
            model_name='contest',
            name='courses',
            field=models.ManyToManyField(related_name='contests', to='runner.course'),
        ),
        migrations.AddField(
            model_name='contest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
        ),
        migrations.AddField(
            model_name='contest',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_contests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contest',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contest',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Contest duration in minutes', null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='is_published',
            field=models.BooleanField(default=False, help_text='When True the contest is visible to all course participants; otherwise only course teachers can see it.'),
        ),
        migrations.AddField(
            model_name='contest',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='source',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='contest',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
