# Generated by Django 5.2.8 on 2025-11-25 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0005_tag_problem_tags'),
        ('runner', '0006_merge_manual'),
    ]

    operations = [
    ]
