# Generated by Django 5.2.8 on 2025-11-26 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0007_alter_contest_options_remove_contest__type_and_more'),
        ('runner', '0007_merge_0005_tag_problem_tags_0006_merge_manual'),
    ]

    operations = [
    ]
