# Generated by Django 5.2.8 on 2025-11-27 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0008_merge_20251126_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='courses',
        ),
        migrations.AddField(
            model_name='contest',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contests', to='runner.course'),
        ),
        migrations.AddField(
            model_name='contest',
            name='status',
            field=models.IntegerField(choices=[(0, 'going'), (1, 'after-solving')], default=0),
        ),
        migrations.AlterField(
            model_name='contest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='source',
            field=models.CharField(blank=True, default='', help_text='Optional source label or namespace for the contest', max_length=255),
        ),
        migrations.AlterField(
            model_name='contest',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
