# Generated by Django 5.2.7 on 2025-12-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0010_course_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='is_rated',
            field=models.BooleanField(default=False, help_text='If true, contest results affect participant rating'),
        ),
        migrations.AddField(
            model_name='contest',
            name='registration_type',
            field=models.CharField(choices=[('open', 'Open'), ('approval', 'By approval'), ('invite', 'By invitation')], default='open', help_text='Who can register / how participants join the contest', max_length=20),
        ),
        migrations.AddField(
            model_name='contest',
            name='scoring',
            field=models.CharField(choices=[('icpc', 'ICPC (penalty by time)'), ('ioi', 'IOI (sum of scores)'), ('partial', 'Partial scoring')], default='ioi', help_text='How points are aggregated for the contest', max_length=20),
        ),
    ]
