# Generated by Django 5.2.8 on 2025-11-27 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("runner", "0010_course_parent"),
    ]

    operations = []
