# Generated by Django 5.2.8 on 2025-12-03 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0011_contest_is_rated_contest_registration_type_and_more'),
        ('runner', '0011_contest_scoring_registration_is_rated'),
    ]

    operations = [
    ]
