# Generated by Django 5.2.8 on 2025-12-10 00:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runner", "0012_merge_20251203_1758"),
    ]

    operations = [
        migrations.AddField(
            model_name="contest",
            name="access_token",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Token for link-based access",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="contest",
            name="access_type",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("private", "Private"),
                    ("link", "By link"),
                ],
                default="public",
                help_text="Controls who can see and join the contest",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="contest",
            name="allowed_participants",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users explicitly allowed to access a private contest",
                related_name="allowed_contests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
