# Generated by Django 5.2.8 on 2025-12-04 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0005_alter_cell_cell_type_alter_notebook_owner'),
        ('runner', '0012_merge_20251203_1758'),
    ]

    operations = [
    ]
