# Generated by Django 5.2.8 on 2025-12-10 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("runner", "0013_contest_access_type_access_token_allowed_participants"),
    ]

    operations = [
        migrations.AddField(
            model_name="contest",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                help_text="Moderation status of the contest",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="contest",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contest",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approved_contests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
