# Generated by Django 5.2.8 on 2025-12-26 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0015_sections_architecture'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='course',
            name='runner_course_parent_idx',
        ),
    ]
