# Generated by Django 5.2.8 on 2026-01-21 19:39
# Index runner_course_parent_idx already removed by 0016_remove_course_runner_course_parent_idx

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0018_notebook_notebook_owner_problem_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='compute_device',
            field=models.CharField(choices=[('cpu', 'CPU'), ('gpu', 'GPU')], default='cpu', max_length=8),
        ),
    ]
