# Generated by Django 5.2.8 on 2026-01-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0015_sections_architecture'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='course',
            name='runner_course_parent_idx',
        ),
        migrations.AddField(
            model_name='notebook',
            name='compute_device',
            field=models.CharField(choices=[('cpu', 'CPU'), ('gpu', 'GPU')], default='cpu', max_length=8),
        ),
    ]
