# Generated by Django 5.2.8 on 2026-01-30 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0016_remove_course_runner_course_parent_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notebooks', to='runner.problem'),
        ),
    ]
