# Generated by Django 5.2.8 on 2026-01-30 07:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0017_notebook_problem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notebook',
            index=models.Index(fields=['owner', 'problem'], name='notebook_owner_problem_idx'),
        ),
        migrations.AddConstraint(
            model_name='notebook',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', False), ('problem__isnull', False)), fields=('owner', 'problem'), name='unique_owner_problem_notebook'),
        ),
    ]
