# Generated by Django 5.2.8 on 2026-02-03 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0016_remove_course_runner_course_parent_idx_and_more'),
        ('runner', '0018_notebook_notebook_owner_problem_idx_and_more'),
    ]

    operations = [
    ]
