# Generated by Django 5.2.8 on 2026-02-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runner", "0019_merge_20260203_1939"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "⏳ В очереди"),
                    ("running", "🏃 Выполняется"),
                    ("accepted", "✅ Протестировано"),
                    ("failed", "❌ Ошибка"),
                    ("validation_error", "⚠️ Ошибка валидации"),
                    ("validated", "✅ Валидировано"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
