# Generated by Django 5.2.8 on 2026-02-06 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0013_merge_20251204_2030'),
        ('runner', '0019_merge_20260203_1939'),
    ]

    operations = [
    ]
