# Generated by Django 5.2.8 on 2026-02-07 22:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0022_rename_sections_add_activity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='courseparticipant',
            index=models.Index(fields=['user', '-last_activity_at'], name='runner_user_activity_idx'),
        ),
    ]
