# Generated by Django 5.2.8 on 2026-02-14 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0020_merge_20260206_2046'),
        ('runner', '0023_section_teachers'),
    ]

    operations = [
    ]
