# Generated by Django 5.2.8 on 2026-02-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0024_merge_0020_merge_20260206_2046_0023_section_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemdata',
            name='text_answer',
            field=models.TextField(blank=True, verbose_name='Правильный текстовый ответ'),
        ),
        migrations.AddField(
            model_name='problemdescriptor',
            name='problem_type',
            field=models.CharField(choices=[('text', 'Text answer'), ('csv', 'CSV / ML task')], default='text', max_length=10),
        ),
    ]
