# Generated by Django 5.2.8 on 2026-02-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0025_problemdata_text_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemdata',
            name='text_answer',
        ),
        migrations.RemoveField(
            model_name='problemdescriptor',
            name='problem_type',
        ),
        migrations.AddField(
            model_name='submission',
            name='raw_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='source',
            field=models.CharField(choices=[('file', 'File upload'), ('text', 'Text input')], default='file', max_length=10),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/'),
        ),
    ]
