# Generated by Django 5.2.8 on 2026-02-20 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0024_problemdescriptor_scoring_fields'),
        ('runner', '0026_remove_problemdata_text_answer_and_more'),
    ]

    operations = [
    ]
