# Generated by Django 5.2.8 on 2026-02-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runner", "0027_merge_20260220_0535"),
    ]

    operations = [
        migrations.AddField(
            model_name="contest",
            name="allow_upsolving",
            field=models.BooleanField(
                default=False,
                help_text="Allow submissions after contest deadline",
            ),
        ),
    ]
