# Generated by Django 5.2.8 on 2026-02-22 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0028_contest_allow_upsolving'),
        ('runner', '0028_profile'),
    ]

    operations = [
    ]
