# Generated by Django 5.2.8 on 2026-03-05 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runner", "0029_merge_0028_contest_allow_upsolving_0028_profile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContestNotification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(choices=[("announcement", "Announcement"), ("question", "Question"), ("answer", "Answer")], max_length=24)),
                ("audience", models.CharField(choices=[("all_participants", "All participants"), ("selected_participants", "Selected participants"), ("teachers", "Teachers"), ("question_author", "Question author")], max_length=32)),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("author", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="contest_notifications_authored", to=settings.AUTH_USER_MODEL)),
                ("contest", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="notifications", to="runner.contest")),
                ("parent", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="answers", to="runner.contestnotification")),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ContestNotificationRecipient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("notification", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="recipient_links", to="runner.contestnotification")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="contest_notification_links", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name="contestnotification",
            index=models.Index(fields=["contest", "created_at"], name="runner_contestnotif_ct_idx"),
        ),
        migrations.AddIndex(
            model_name="contestnotification",
            index=models.Index(fields=["contest", "kind"], name="runner_contestnotif_kind_idx"),
        ),
        migrations.AddIndex(
            model_name="contestnotification",
            index=models.Index(fields=["parent", "created_at"], name="runner_contestnotif_parent_idx"),
        ),
        migrations.AddIndex(
            model_name="contestnotificationrecipient",
            index=models.Index(fields=["user", "is_read"], name="runner_cntnotifrec_u_idx"),
        ),
        migrations.AddIndex(
            model_name="contestnotificationrecipient",
            index=models.Index(fields=["notification", "user"], name="runner_cntnotifrec_n_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="contestnotificationrecipient",
            unique_together={("notification", "user")},
        ),
    ]
