# Generated by Django 5.2.8 on 2026-03-09 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runner", "0033_notebookfolder_notebook_folder_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notebookfolder",
            name="parent",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="children", to="runner.notebookfolder"),
        ),
        migrations.AddIndex(
            model_name="notebookfolder",
            index=models.Index(fields=["owner", "parent"], name="nb_folder_owner_parent_idx"),
            model_name='notebookfolder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='runner.notebookfolder'),
        ),
        migrations.AddIndex(
            model_name='notebookfolder',
            index=models.Index(fields=['owner', 'parent'], name='nb_folder_owner_parent_idx'),
        ),
    ]
