# Generated by Django 5.2.8 on 2026-04-16 17:40

import django.db.models.deletion
import runner.models.profile
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0037_course_section_publication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof', models.FileField(upload_to=runner.models.profile.teacher_request_upload_path)),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], db_index=True, default='pending', max_length=20)),
                ('review_comment', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_teacher_access_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_access_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заявка на права учителя',
                'verbose_name_plural': 'Заявки на права учителя',
                'ordering': ('-created_at',),
            },
        ),
    ]
