from django.urls import path
from .views import (
    CourseCreateView,
    CourseParticipantsUpdateView,
    CourseSelfEnrollView,
    CourseTreeView,
    SectionCreateView,
    SubmissionCreateView,
    MySubmissionsListView,
    CreateNotebookView,
    SubmissionDetailView,
    CreateNotebookSessionView,
    ResetSessionView,
    RunCellView,
    SessionFilesView,
    SessionFileDownloadView,
    SessionFileUploadView,
    StopSessionView,
)

urlpatterns = [
    path("submissions/", SubmissionCreateView.as_view(), name="submission-create"),
    path("submissions/mine/", MySubmissionsListView.as_view(), name="submission-list-mine"),
    path("notebooks/", CreateNotebookView.as_view(), name="notebook-create"),
    path("submissions/<int:pk>/", SubmissionDetailView.as_view(), name="submission-detail"),
    path("sessions/notebook/", CreateNotebookSessionView.as_view(), name="notebook-session-create"),
    path("sessions/reset/", ResetSessionView.as_view(), name="session-reset"),
    path("sessions/stop/", StopSessionView.as_view(), name="session-stop"),
    path("sessions/files/", SessionFilesView.as_view(), name="session-files"),
    path("sessions/files/upload/", SessionFileUploadView.as_view(), name="session-file-upload"),
    path("sessions/file/", SessionFileDownloadView.as_view(), name="session-file-download"),
    path("cells/run/", RunCellView.as_view(), name="run-cell"),
    path("courses/", CourseCreateView.as_view(), name="course-create"),
    path("courses/tree/", CourseTreeView.as_view(), name="course-tree"),
    path("sections/", SectionCreateView.as_view(), name="section-create"),
    path(
        "courses/<int:course_id>/participants/",
        CourseParticipantsUpdateView.as_view(),
        name="course-participants-update",
    ),
    path(
        "courses/<int:course_id>/enroll/",
        CourseSelfEnrollView.as_view(),
        name="course-self-enroll",
    ),
]
