from django.urls import path
from .views import (
    CourseCreateView,
    CourseParticipantsUpdateView,
    CourseSelfEnrollView,
    CourseTreeView,
    SectionCreateView,
    SectionUpdateView,
    SectionDeleteView,
    SectionListView,
    SectionDetailView,
    SubmissionCreateView,
    MySubmissionsListView,
    CreateNotebookSessionView,
    ResetSessionView,
    RunCellView,
    SessionFilesView,
    SessionFileDownloadView,
    SessionFileUploadView,
    StopSessionView,
)

urlpatterns = [
    path("submissions/", SubmissionCreateView.as_view(), name="submission-create"),
    path("submissions/mine/", MySubmissionsListView.as_view(), name="submission-list-mine"),
    path("sessions/notebook/", CreateNotebookSessionView.as_view(), name="notebook-session-create"),
    path("sessions/reset/", ResetSessionView.as_view(), name="session-reset"),
    path("sessions/stop/", StopSessionView.as_view(), name="session-stop"),
    path("sessions/files/", SessionFilesView.as_view(), name="session-files"),
    path("sessions/files/upload/", SessionFileUploadView.as_view(), name="session-file-upload"),
    path("sessions/file/", SessionFileDownloadView.as_view(), name="session-file-download"),
    path("cells/run/", RunCellView.as_view(), name="run-cell"),
    path("courses/", CourseCreateView.as_view(), name="course-create"),
    path("courses/tree/", CourseTreeView.as_view(), name="course-tree"),
    path(
        "courses/<int:course_id>/participants/",
        CourseParticipantsUpdateView.as_view(),
        name="course-participants-update",
    ),
    path(
        "courses/<int:course_id>/enroll/",
        CourseSelfEnrollView.as_view(),
        name="course-self-enroll",
    ),
    # Sections
    path("sections/", SectionCreateView.as_view(), name="section-create"),
    path("sections/list/", SectionListView.as_view(), name="section-list"),
    path("sections/<int:section_id>/", SectionDetailView.as_view(), name="section-detail"),
    path("sections/<int:section_id>/update/", SectionUpdateView.as_view(), name="section-update"),
    path("sections/<int:section_id>/delete/", SectionDeleteView.as_view(), name="section-delete"),
]
