from django.urls import path
from .views import (
    CourseCreateView,
    CourseParticipantsUpdateView,
    CourseSelfEnrollView,
    CourseTreeView,
    SectionCreateView,
    SectionDeleteView,
    HomeSidebarView,
    FavoriteCoursesListView,
    FavoriteCoursesAddView,
    FavoriteCoursesRemoveView,
    FavoriteCoursesReorderView,
    SubmissionCreateView,
    MySubmissionsListView,
    CreateNotebookView,
    SubmissionDetailView,
    ProblemSubmissionsListView,
    CreateNotebookSessionView,
    ResetSessionView,
    RunCellView,
    RunCellInputView,
    RunCellStreamStartView,
    RunCellStreamStatusView,
    SessionFilesView,
    SessionFileDownloadView,
    SessionFileUploadView,
    SessionFilePreviewView,
    StopSessionView,
)

urlpatterns = [
    path("submissions/", SubmissionCreateView.as_view(), name="submission-create"),
    path("submissions/mine/", MySubmissionsListView.as_view(), name="submission-list-mine"),
    path("notebooks/", CreateNotebookView.as_view(), name="notebook-create"),
    path("submissions/<int:pk>/", SubmissionDetailView.as_view(), name="submission-detail"),
    path("submissions/problem/<int:problem_id>/", ProblemSubmissionsListView.as_view(), name="submission-list-problem"),
    path("sessions/notebook/", CreateNotebookSessionView.as_view(), name="notebook-session-create"),
    path("sessions/reset/", ResetSessionView.as_view(), name="session-reset"),
    path("sessions/stop/", StopSessionView.as_view(), name="session-stop"),
    path("sessions/files/", SessionFilesView.as_view(), name="session-files"),
    path("sessions/files/upload/", SessionFileUploadView.as_view(), name="session-file-upload"),
    path("sessions/file/", SessionFileDownloadView.as_view(), name="session-file-download"),
    path("sessions/file/preview/", SessionFilePreviewView.as_view(), name="session-file-preview"),
    path("cells/run/", RunCellView.as_view(), name="run-cell"),
    path("cells/run/input/", RunCellInputView.as_view(), name="run-cell-input"),
    path("cells/run/stream/", RunCellStreamStartView.as_view(), name="run-cell-stream-start"),
    path("cells/run/stream/status/", RunCellStreamStatusView.as_view(), name="run-cell-stream-status"),
    path("courses/", CourseCreateView.as_view(), name="course-create"),
    path("courses/tree/", CourseTreeView.as_view(), name="course-tree"),
    path("sections/", SectionCreateView.as_view(), name="section-create"),
    path("sections/<int:section_id>/delete/", SectionDeleteView.as_view(), name="section-delete"),
    path("home/sidebar/", HomeSidebarView.as_view(), name="home-sidebar"),
    path("favorites/courses/", FavoriteCoursesListView.as_view(), name="favorite-courses"),
    path("favorites/courses/add/", FavoriteCoursesAddView.as_view(), name="favorite-courses-add"),
    path("favorites/courses/remove/", FavoriteCoursesRemoveView.as_view(), name="favorite-courses-remove"),
    path("favorites/courses/reorder/", FavoriteCoursesReorderView.as_view(), name="favorite-courses-reorder"),
    path(
        "courses/<int:course_id>/participants/",
        CourseParticipantsUpdateView.as_view(),
        name="course-participants-update",
    ),
    path(
        "courses/<int:course_id>/enroll/",
        CourseSelfEnrollView.as_view(),
        name="course-self-enroll",
    ),
]
