# Generated by Django 5.2.8 on 2026-02-11
# Этот файл создается, если таблица system_metrics уже существует в базе данных
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        # Пустая миграция, так как таблица уже существует
        # Это позволяет Django считать, что миграция выполнена
    ]